import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-cyber-insurance-incident-claim-recovery",
  "engine": "recovery",
  "title": "Cyber Insurance Incident Claim Recovery",
  "shortTitle": "Cyber Insurance Incident Claim Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through cyber insurance incident claim recovery",
  "industry": "Cyber Claim Financial Recovery",
  "uiPort": 4618,
  "apiPort": 5618,
  "accent": "#4338ca",
  "currency": "USD",
  "primaryOutcome": "Cyber Insurance Incident Claim Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "settledAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Insurer Settlement",
    "expectedLabel": "Supported Covered Loss",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Cyber Insurance Incident Claim Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("policy-endorsement-library","CII01","Policy endorsement library","Execute policy endorsement library using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed policy endorsement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Policy endorsement library Reference","text","CII01-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("incident-timeline","CII02","Incident timeline","Execute incident timeline using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed incident timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Incident timeline Reference","text","CII02-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("notification-deadline-control","CII03","Notification deadline control","Execute notification deadline control using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed notification deadline control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Notification deadline control Reference","text","CII03-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("forensic-vendor-cost-ingestion","CII04","Forensic vendor cost ingestion","Execute forensic vendor cost ingestion using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed forensic vendor cost ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Forensic vendor cost ingestion Reference","text","CII04-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("legal-counsel-costs","CII05","Legal counsel costs","Execute legal counsel costs using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed legal counsel costs decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Legal counsel costs Reference","text","CII05-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("notification-monitoring-expense","CII06","Notification monitoring expense","Execute notification monitoring expense using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed notification monitoring expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Notification monitoring expense Reference","text","CII06-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("data-restoration-expense","CII07","Data restoration expense","Execute data restoration expense using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed data restoration expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Data restoration expense Reference","text","CII07-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("business-interruption-calculation","CII08","Business interruption calculation","Execute business interruption calculation using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed business interruption calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Business interruption calculation Reference","text","CII08-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("cyber-extortion-expense","CII09","Cyber extortion expense","Execute cyber extortion expense using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed cyber extortion expense decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Cyber extortion expense Reference","text","CII09-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("regulatory-defense-costs","CII10","Regulatory defense costs","Execute regulatory defense costs using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed regulatory defense costs decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Regulatory defense costs Reference","text","CII10-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("social-engineering-analysis","CII11","Social engineering analysis","Execute social engineering analysis using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed social engineering analysis decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Social engineering analysis Reference","text","CII11-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("consent-panel-vendor-control","CII12","Consent panel vendor control","Execute consent panel vendor control using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed consent panel vendor control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Consent panel vendor control Reference","text","CII12-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("proof-of-loss-package","CII13","Proof-of-loss package","Execute proof-of-loss package using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed proof-of-loss package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Proof-of-loss package Reference","text","CII13-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("insurer-request-workflow","CII14","Insurer request workflow","Execute insurer request workflow using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed insurer request workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Insurer request workflow Reference","text","CII14-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]}),
feature("settlement-reconciliation","CII15","Settlement reconciliation","Execute settlement reconciliation using cyber policies, endorsements, incidents, notification deadlines, forensic vendors, breach counsel, restoration, interruption, extortion, regulatory costs, consent, proof of loss, and settlements.","Produce a governed settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Insured / Cyber Incident","text","Insured / Cyber Incident · Standard Case"],["caseReference","Settlement reconciliation Reference","text","CII15-2026-001"],["settledAmount","Insurer Settlement","currency",919500],["eligibleAmount","Supported Covered Loss","currency",1085010],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"settledAmount",subjects:["Policy endorsement library case","Incident timeline case","Notification deadline control case","Forensic vendor cost ingestion case","Legal counsel costs case"]})
]);
